### ISSUE TITLE
Role of Lambda* classes inside model autoencoders

### ISSUE THREAD

**Issue by vinsis** [pietrocarbo/deep-transfer#2]
Another question: it seems these classes [here](https://github.com/pietrocarbo/deep-transfer/blob/master/models/autoencoder_vgg19/vgg19_1/vgg_normalised_conv1_1.py#L9-L31) are doing nothing. The code works the same way without them. Just curious - what was the intended role of these classes?

**Comment by pietrocarbo** [comment]
Yes, they have no use currently.

They were part of the output produced by this [tool](https://github.com/clcarwin/convert_torch_to_pytorch) used to convert the original .t7 weight files into into the more readable and cross-platform .pth format.
